//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Janeshop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_JANESHOPEntities1 : DbContext
    {
        public DB_JANESHOPEntities1()
            : base("name=DB_JANESHOPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_CART> TBL_CART { get; set; }
        public virtual DbSet<TBL_DISTRICT> TBL_DISTRICT { get; set; }
        public virtual DbSet<TBL_GEN_ID> TBL_GEN_ID { get; set; }
        public virtual DbSet<TBL_ORDER> TBL_ORDER { get; set; }
        public virtual DbSet<TBL_OWNER> TBL_OWNER { get; set; }
        public virtual DbSet<TBL_PRODUCT_PICTURE> TBL_PRODUCT_PICTURE { get; set; }
        public virtual DbSet<TBL_PRODUCT_TYPE> TBL_PRODUCT_TYPE { get; set; }
        public virtual DbSet<TBL_USER> TBL_USER { get; set; }
        public virtual DbSet<TBL_ORDER_DETAIL> TBL_ORDER_DETAIL { get; set; }
        public virtual DbSet<TBL_PRODUCT> TBL_PRODUCT { get; set; }
        public virtual DbSet<TBL_BANK> TBL_BANK { get; set; }
    }
}
